# Problem 1

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 11, 5)
print(matris)
# 3 - matris'in boyutunu öğrenin
print( matris.shape)
# 4 - matris'i yeniden boyutlandırın
yeni_matris = matris.reshape(1, 5)
print(yeni_matris)
# 5 - matris'in boyut sayısını öğrenin
print(yeni_matris.ndim)

[5 4 0 8 1]
(5,)
[[5 4 0 8 1]]
2


# Problem 2

In [6]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.random.choice([1, 3, 5, 7, 9], size=(2, 3))
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
parca1 = matris[:, :2]
parca2 = matris[:, 2:]
print(parca1)
print(parca2)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis_matris = np.concatenate((parca1, parca2), axis=1)
print(birlesmis_matris)

[[7 1 5]
 [3 3 9]]
[[7 1]
 [3 3]]
[[5]
 [9]]
[[7 1 5]
 [3 3 9]]


# Problem 3

In [9]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.randint(5, 101, size=(2, 5))
print(matris)

# 2 - matris'in özelliklerini inceleyin
matris.shape
matris.ndim
matris.size

[[40 11 95 70 87]
 [80 14 57 27 94]]


8